using System.Text.Json;
using System.Text.Json.Serialization;
using PayabliApi.Core;

namespace PayabliApi;

[Serializable]
public record NotificationContent : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// The notification's event name.
    /// </summary>
    [JsonPropertyName("eventType")]
    public NotificationContentEventType? EventType { get; set; }

    /// <summary>
    /// Indicate the format of report file to be generated by the engine.
    /// Used for `method` = *report-email* and *report-web*.
    /// </summary>
    [JsonPropertyName("fileFormat")]
    public NotificationContentFileFormat? FileFormat { get; set; }

    /// <summary>
    /// Array of pairs key:value to insert in request body to target in **method** = *web* or *report-web*.
    /// </summary>
    [JsonPropertyName("internalData")]
    public IEnumerable<KeyValueDuo>? InternalData { get; set; }

    /// <summary>
    /// The kind report to generate. For [automated reports](/developers/developer-guides/notifications-and-webhooks-overview#automated-reports) only.
    /// </summary>
    [JsonPropertyName("reportName")]
    public NotificationContentReportName? ReportName { get; set; }

    [JsonPropertyName("timeZone")]
    public int? TimeZone { get; set; }

    /// <summary>
    /// Used internally to reference the entity or object generating the event.
    /// </summary>
    [JsonPropertyName("transactionId")]
    public string? TransactionId { get; set; }

    /// <summary>
    /// Array of pairs key:value to insert in header of request to target in **method** = *web* or *report-web*.
    /// </summary>
    [JsonPropertyName("webHeaderParameters")]
    public IEnumerable<KeyValueDuo>? WebHeaderParameters { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
