using global::System.Text.Json;
using global::System.Text.Json.Serialization;
using PayabliApi.Core;

namespace PayabliApi;

[Serializable]
public record StatBasicExtendedQueryRecord : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// The time bucket for this row, formatted according to the query's `freq` (for example, `2025-11` for a monthly bucket). The response returns one object per bucket across the requested range.
    /// </summary>
    [JsonPropertyName("statX")]
    public required string StatX { get; set; }

    /// <summary>
    /// Cumulative number of vendors, as a running total through the end of this bucket rather than a per-bucket count. On the payout (money out) side, "customers" are vendors.
    /// </summary>
    [JsonPropertyName("outCustomers")]
    public required int OutCustomers { get; set; }

    /// <summary>
    /// Number of vendors created during this bucket, scoped to the paypoint (`level` 2) or organization (`level` 0).
    /// </summary>
    [JsonPropertyName("outNewCustomers")]
    public required int OutNewCustomers { get; set; }

    /// <summary>
    /// Count of payout (money out) transactions. The payout method counts (`outCardTransactions`, `outVCardTransactions`, `outACHTransactions`, `outCheckTransactions`, `outPendingMethodTransactions`, `outRTPTransactions`, `outWireTransactions`) are mutually exclusive and together account for this total.
    /// </summary>
    [JsonPropertyName("outTransactions")]
    public required int OutTransactions { get; set; }

    /// <summary>
    /// Count of payout transactions generated by a recurring schedule.
    /// </summary>
    [JsonPropertyName("outSubscriptionsPaid")]
    public required int OutSubscriptionsPaid { get; set; }

    /// <summary>
    /// Count of payout transactions sent by pCard.
    /// </summary>
    [JsonPropertyName("outCardTransactions")]
    public required int OutCardTransactions { get; set; }

    /// <summary>
    /// Count of payout transactions sent by virtual card (vCard).
    /// </summary>
    [JsonPropertyName("outVCardTransactions")]
    public required int OutVCardTransactions { get; set; }

    /// <summary>
    /// Count of payout transactions sent by ACH.
    /// </summary>
    [JsonPropertyName("outACHTransactions")]
    public required int OutAchTransactions { get; set; }

    /// <summary>
    /// Count of payout transactions sent by check.
    /// </summary>
    [JsonPropertyName("outCheckTransactions")]
    public required int OutCheckTransactions { get; set; }

    /// <summary>
    /// Count of payout transactions held as Managed Payables, where the payout method isn't assigned yet.
    /// </summary>
    [JsonPropertyName("outPendingMethodTransactions")]
    public required int OutPendingMethodTransactions { get; set; }

    /// <summary>
    /// Count of payout transactions sent by real-time payments (RTP).
    /// </summary>
    [JsonPropertyName("outRTPTransactions")]
    public required int OutRtpTransactions { get; set; }

    /// <summary>
    /// Total value of RTP payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outRTPVolume")]
    public required double OutRtpVolume { get; set; }

    /// <summary>
    /// Count of payout transactions sent by wire.
    /// </summary>
    [JsonPropertyName("outWireTransactions")]
    public required int OutWireTransactions { get; set; }

    /// <summary>
    /// Total value of wire payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outWireVolume")]
    public required double OutWireVolume { get; set; }

    /// <summary>
    /// Total payout value, net of fees.
    /// </summary>
    [JsonPropertyName("outTransactionsVolume")]
    public required double OutTransactionsVolume { get; set; }

    /// <summary>
    /// Total value of recurring payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outSubscriptionsPaidVolume")]
    public required double OutSubscriptionsPaidVolume { get; set; }

    /// <summary>
    /// Total value of pCard payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outCardVolume")]
    public required double OutCardVolume { get; set; }

    /// <summary>
    /// Total value of vCard payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outVCardVolume")]
    public required double OutVCardVolume { get; set; }

    /// <summary>
    /// Total value of ACH payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outACHVolume")]
    public required double OutAchVolume { get; set; }

    /// <summary>
    /// Total value of check payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outCheckVolume")]
    public required double OutCheckVolume { get; set; }

    /// <summary>
    /// Total value of Managed Payables payouts, net of fees.
    /// </summary>
    [JsonPropertyName("outPendingMethodVolume")]
    public required double OutPendingMethodVolume { get; set; }

    /// <summary>
    /// Count of approved inbound (money in) transactions. This counts approved transactions only and leaves out declines. The payment method counts (`inCardTransactions`, `inACHTransactions`, `inCheckTransactions`, `inCashTransactions`, `inWalletTransactions`) are mutually exclusive and sum to this total.
    /// </summary>
    [JsonPropertyName("inTransactions")]
    public required int InTransactions { get; set; }

    /// <summary>
    /// Count of approved inbound transactions charged by a recurring schedule. This is a subset of `inTransactions`, not an amount to add on top of it.
    /// </summary>
    [JsonPropertyName("inSubscriptionsPaid")]
    public required int InSubscriptionsPaid { get; set; }

    /// <summary>
    /// Cumulative number of customers, as a running total through the end of this bucket rather than a per-bucket count.
    /// </summary>
    [JsonPropertyName("inCustomers")]
    public required int InCustomers { get; set; }

    /// <summary>
    /// Number of customers created during this bucket, scoped to the paypoint (`level` 2) or organization (`level` 0).
    /// </summary>
    [JsonPropertyName("inNewCustomers")]
    public required int InNewCustomers { get; set; }

    /// <summary>
    /// Count of approved inbound card transactions, including card, cloud device, and in-person device payments.
    /// </summary>
    [JsonPropertyName("inCardTransactions")]
    public required int InCardTransactions { get; set; }

    /// <summary>
    /// Count of approved inbound ACH transactions.
    /// </summary>
    [JsonPropertyName("inACHTransactions")]
    public required int InAchTransactions { get; set; }

    /// <summary>
    /// Count of approved inbound check transactions.
    /// </summary>
    [JsonPropertyName("inCheckTransactions")]
    public required int InCheckTransactions { get; set; }

    /// <summary>
    /// Count of approved inbound cash transactions.
    /// </summary>
    [JsonPropertyName("inCashTransactions")]
    public required int InCashTransactions { get; set; }

    /// <summary>
    /// Count of approved inbound digital wallet transactions.
    /// </summary>
    [JsonPropertyName("inWalletTransactions")]
    public required int InWalletTransactions { get; set; }

    /// <summary>
    /// Count of card chargebacks recorded. Tracked separately from `inACHReturns`.
    /// </summary>
    [JsonPropertyName("inCardChargeBacks")]
    public required int InCardChargeBacks { get; set; }

    /// <summary>
    /// Count of ACH returns recorded.
    /// </summary>
    [JsonPropertyName("inACHReturns")]
    public required int InAchReturns { get; set; }

    /// <summary>
    /// Total approved inbound value, net of fees.
    /// </summary>
    [JsonPropertyName("inTransactionsVolume")]
    public required double InTransactionsVolume { get; set; }

    /// <summary>
    /// Total value of approved recurring inbound transactions, net of fees.
    /// </summary>
    [JsonPropertyName("inSubscriptionsPaidVolume")]
    public required double InSubscriptionsPaidVolume { get; set; }

    /// <summary>
    /// Total approved card value, net of fees.
    /// </summary>
    [JsonPropertyName("inCardVolume")]
    public required double InCardVolume { get; set; }

    /// <summary>
    /// Total approved ACH value, net of fees.
    /// </summary>
    [JsonPropertyName("inACHVolume")]
    public required double InAchVolume { get; set; }

    /// <summary>
    /// Total approved check value, net of fees.
    /// </summary>
    [JsonPropertyName("inCheckVolume")]
    public required double InCheckVolume { get; set; }

    /// <summary>
    /// Total approved cash value, net of fees.
    /// </summary>
    [JsonPropertyName("inCashVolume")]
    public required double InCashVolume { get; set; }

    /// <summary>
    /// Total approved digital wallet value, net of fees.
    /// </summary>
    [JsonPropertyName("inWalletVolume")]
    public required double InWalletVolume { get; set; }

    /// <summary>
    /// Total value of card chargebacks.
    /// </summary>
    [JsonPropertyName("inCardChargeBackVolume")]
    public required double InCardChargeBackVolume { get; set; }

    /// <summary>
    /// Total value of ACH returns.
    /// </summary>
    [JsonPropertyName("inACHReturnsVolume")]
    public required double InAchReturnsVolume { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
