using OneOf;

namespace PayabliApi;

public partial interface INotificationClient
{
    /// <summary>
    /// Create a new notification or autogenerated report.
    /// </summary>
    WithRawResponseTask<PayabliApiResponseNotifications> AddNotificationAsync(
        OneOf<NotificationStandardRequest, NotificationReportRequest> request,
        RequestOptions? options = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Deletes a single notification or autogenerated report.
    /// </summary>
    WithRawResponseTask<PayabliApiResponseNotifications> DeleteNotificationAsync(
        string nId,
        RequestOptions? options = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Retrieves a single notification or autogenerated report's details.
    /// </summary>
    WithRawResponseTask<NotificationQueryRecord> GetNotificationAsync(
        string nId,
        RequestOptions? options = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Update a notification or autogenerated report.
    /// </summary>
    WithRawResponseTask<PayabliApiResponseNotifications> UpdateNotificationAsync(
        string nId,
        OneOf<NotificationStandardRequest, NotificationReportRequest> request,
        RequestOptions? options = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Gets a copy of a generated report by ID.
    /// </summary>
    WithRawResponseTask<Dictionary<string, object?>> GetReportFileAsync(
        long id,
        RequestOptions? options = null,
        CancellationToken cancellationToken = default
    );
}
