using System.Globalization;
using System.Text.Json;
using NUnit.Framework;
using PayabliApi;
using PayabliApi.Core;

namespace PayabliApi.Test;

[TestFixture]
public class VendorQueryRecordTest
{
    [NUnit.Framework.Test]
    public void TestDeserialization()
    {
        var json = """
            {
              "VendorNumber": "1234",
              "Name1": "Herman's Coatings",
              "Name2": "Herman's Coating Supply Company, LLC",
              "EIN": "123456789",
              "Phone": "212-555-1234",
              "Email": "example@email.com",
              "RemitEmail": null,
              "Address1": "123 Ocean Drive",
              "Address2": "Suite 400",
              "City": "Bristol",
              "State": "GA",
              "Zip": "31113",
              "Country": "US",
              "Mcc": "7777",
              "LocationCode": "LOC123",
              "Contacts": {
                "ContactEmail": "eric@martinezcoatings.com",
                "ContactName": "Eric Martinez",
                "ContactPhone": "5555555555",
                "ContactTitle": "Owner"
              },
              "BillingData": {
                "id": 123456,
                "accountId": "bank-account-001",
                "nickname": "Main Checking Account",
                "bankName": "Example Bank",
                "routingAccount": "123456789",
                "accountNumber": "9876543210",
                "typeAccount": "Checking",
                "bankAccountHolderName": "John Doe",
                "bankAccountHolderType": "Business",
                "bankAccountFunction": 2,
                "verified": true,
                "status": 1,
                "services": [],
                "default": true
              },
              "PaymentMethod": null,
              "VendorStatus": 1,
              "VendorId": 1,
              "EnrollmentStatus": null,
              "Summary": {
                "ActiveBills": 2,
                "PendingBills": 4,
                "InTransitBills": 3,
                "PaidBills": 18,
                "OverdueBills": 1,
                "ApprovedBills": 5,
                "DisapprovedBills": 1,
                "TotalBills": 34,
                "ActiveBillsAmount": 1250.75,
                "PendingBillsAmount": 2890.5,
                "InTransitBillsAmount": 1675.25,
                "PaidBillsAmount": 15420.8,
                "OverdueBillsAmount": 425,
                "ApprovedBillsAmount": 3240.9,
                "DisapprovedBillsAmount": 180,
                "TotalBillsAmount": 25083.2
              },
              "PaypointLegalname": "Sunshine Services, LLC",
              "PaypointDbaname": "Sunshine Gutters",
              "PaypointEntryname": "d193cf9a46",
              "ParentOrgName": "PropertyManager Pro",
              "ParentOrgId": 1000,
              "CreatedDate": "2022-07-01T15:00:01Z",
              "LastUpdated": "2022-07-01T15:00:01Z",
              "remitAddress1": "123 Walnut Street",
              "remitAddress2": "Suite 900",
              "remitCity": "Miami",
              "remitState": "FL",
              "remitZip": "31113",
              "remitCountry": "US",
              "payeeName1": "payeeName1",
              "payeeName2": "payeeName2",
              "customField1": "",
              "customField2": "",
              "customerVendorAccount": "123-456",
              "InternalReferenceId": 1000000,
              "additionalData": null,
              "externalPaypointID": "Paypoint-100",
              "StoredMethods": []
            }
            """;
        var expectedObject = new VendorQueryRecord
        {
            VendorNumber = "1234",
            Name1 = "Herman's Coatings",
            Name2 = "Herman's Coating Supply Company, LLC",
            Ein = "123456789",
            Phone = "212-555-1234",
            Email = "example@email.com",
            RemitEmail = null,
            Address1 = "123 Ocean Drive",
            Address2 = "Suite 400",
            City = "Bristol",
            State = "GA",
            Zip = "31113",
            Country = "US",
            Mcc = "7777",
            LocationCode = "LOC123",
            Contacts = new ContactsResponse
            {
                ContactEmail = "eric@martinezcoatings.com",
                ContactName = "Eric Martinez",
                ContactPhone = "5555555555",
                ContactTitle = "Owner",
            },
            BillingData = new BillingDataResponse
            {
                Id = 123456,
                AccountId = "bank-account-001",
                Nickname = "Main Checking Account",
                BankName = "Example Bank",
                RoutingAccount = "123456789",
                AccountNumber = "9876543210",
                TypeAccount = TypeAccount.Checking,
                BankAccountHolderName = "John Doe",
                BankAccountHolderType = BankAccountHolderType.Business,
                BankAccountFunction = 2,
                Verified = true,
                Status = 1,
                Services = new List<object>() { },
                Default = true,
            },
            PaymentMethod = null,
            VendorStatus = 1,
            VendorId = 1,
            EnrollmentStatus = null,
            Summary = new VendorSummary
            {
                ActiveBills = 2,
                PendingBills = 4,
                InTransitBills = 3,
                PaidBills = 18,
                OverdueBills = 1,
                ApprovedBills = 5,
                DisapprovedBills = 1,
                TotalBills = 34,
                ActiveBillsAmount = 1250.75,
                PendingBillsAmount = 2890.5,
                InTransitBillsAmount = 1675.25,
                PaidBillsAmount = 15420.8,
                OverdueBillsAmount = 425,
                ApprovedBillsAmount = 3240.9,
                DisapprovedBillsAmount = 180,
                TotalBillsAmount = 25083.2,
            },
            PaypointLegalname = "Sunshine Services, LLC",
            PaypointDbaname = "Sunshine Gutters",
            PaypointEntryname = "d193cf9a46",
            ParentOrgName = "PropertyManager Pro",
            ParentOrgId = 1000,
            CreatedDate = DateTime.Parse(
                "2022-07-01T15:00:01.000Z",
                null,
                DateTimeStyles.AdjustToUniversal
            ),
            LastUpdated = DateTime.Parse(
                "2022-07-01T15:00:01.000Z",
                null,
                DateTimeStyles.AdjustToUniversal
            ),
            RemitAddress1 = "123 Walnut Street",
            RemitAddress2 = "Suite 900",
            RemitCity = "Miami",
            RemitState = "FL",
            RemitZip = "31113",
            RemitCountry = "US",
            PayeeName1 = "payeeName1",
            PayeeName2 = "payeeName2",
            CustomField1 = "",
            CustomField2 = "",
            CustomerVendorAccount = "123-456",
            InternalReferenceId = 1000000,
            AdditionalData = null,
            ExternalPaypointId = "Paypoint-100",
            StoredMethods = new List<VendorResponseStoredMethod>() { },
        };
        var deserializedObject = JsonUtils.Deserialize<VendorQueryRecord>(json);
        Assert.That(deserializedObject, Is.EqualTo(expectedObject).UsingDefaults());
    }

    [NUnit.Framework.Test]
    public void TestSerialization()
    {
        var expectedJson = """
            {
              "VendorNumber": "1234",
              "Name1": "Herman's Coatings",
              "Name2": "Herman's Coating Supply Company, LLC",
              "EIN": "123456789",
              "Phone": "212-555-1234",
              "Email": "example@email.com",
              "RemitEmail": null,
              "Address1": "123 Ocean Drive",
              "Address2": "Suite 400",
              "City": "Bristol",
              "State": "GA",
              "Zip": "31113",
              "Country": "US",
              "Mcc": "7777",
              "LocationCode": "LOC123",
              "Contacts": {
                "ContactEmail": "eric@martinezcoatings.com",
                "ContactName": "Eric Martinez",
                "ContactPhone": "5555555555",
                "ContactTitle": "Owner"
              },
              "BillingData": {
                "id": 123456,
                "accountId": "bank-account-001",
                "nickname": "Main Checking Account",
                "bankName": "Example Bank",
                "routingAccount": "123456789",
                "accountNumber": "9876543210",
                "typeAccount": "Checking",
                "bankAccountHolderName": "John Doe",
                "bankAccountHolderType": "Business",
                "bankAccountFunction": 2,
                "verified": true,
                "status": 1,
                "services": [],
                "default": true
              },
              "PaymentMethod": null,
              "VendorStatus": 1,
              "VendorId": 1,
              "EnrollmentStatus": null,
              "Summary": {
                "ActiveBills": 2,
                "PendingBills": 4,
                "InTransitBills": 3,
                "PaidBills": 18,
                "OverdueBills": 1,
                "ApprovedBills": 5,
                "DisapprovedBills": 1,
                "TotalBills": 34,
                "ActiveBillsAmount": 1250.75,
                "PendingBillsAmount": 2890.5,
                "InTransitBillsAmount": 1675.25,
                "PaidBillsAmount": 15420.8,
                "OverdueBillsAmount": 425,
                "ApprovedBillsAmount": 3240.9,
                "DisapprovedBillsAmount": 180,
                "TotalBillsAmount": 25083.2
              },
              "PaypointLegalname": "Sunshine Services, LLC",
              "PaypointDbaname": "Sunshine Gutters",
              "PaypointEntryname": "d193cf9a46",
              "ParentOrgName": "PropertyManager Pro",
              "ParentOrgId": 1000,
              "CreatedDate": "2022-07-01T15:00:01Z",
              "LastUpdated": "2022-07-01T15:00:01Z",
              "remitAddress1": "123 Walnut Street",
              "remitAddress2": "Suite 900",
              "remitCity": "Miami",
              "remitState": "FL",
              "remitZip": "31113",
              "remitCountry": "US",
              "payeeName1": "payeeName1",
              "payeeName2": "payeeName2",
              "customField1": "",
              "customField2": "",
              "customerVendorAccount": "123-456",
              "InternalReferenceId": 1000000,
              "additionalData": null,
              "externalPaypointID": "Paypoint-100",
              "StoredMethods": []
            }
            """;
        var actualObj = new VendorQueryRecord
        {
            VendorNumber = "1234",
            Name1 = "Herman's Coatings",
            Name2 = "Herman's Coating Supply Company, LLC",
            Ein = "123456789",
            Phone = "212-555-1234",
            Email = "example@email.com",
            RemitEmail = null,
            Address1 = "123 Ocean Drive",
            Address2 = "Suite 400",
            City = "Bristol",
            State = "GA",
            Zip = "31113",
            Country = "US",
            Mcc = "7777",
            LocationCode = "LOC123",
            Contacts = new ContactsResponse
            {
                ContactEmail = "eric@martinezcoatings.com",
                ContactName = "Eric Martinez",
                ContactPhone = "5555555555",
                ContactTitle = "Owner",
            },
            BillingData = new BillingDataResponse
            {
                Id = 123456,
                AccountId = "bank-account-001",
                Nickname = "Main Checking Account",
                BankName = "Example Bank",
                RoutingAccount = "123456789",
                AccountNumber = "9876543210",
                TypeAccount = TypeAccount.Checking,
                BankAccountHolderName = "John Doe",
                BankAccountHolderType = BankAccountHolderType.Business,
                BankAccountFunction = 2,
                Verified = true,
                Status = 1,
                Services = new List<object>() { },
                Default = true,
            },
            PaymentMethod = null,
            VendorStatus = 1,
            VendorId = 1,
            EnrollmentStatus = null,
            Summary = new VendorSummary
            {
                ActiveBills = 2,
                PendingBills = 4,
                InTransitBills = 3,
                PaidBills = 18,
                OverdueBills = 1,
                ApprovedBills = 5,
                DisapprovedBills = 1,
                TotalBills = 34,
                ActiveBillsAmount = 1250.75,
                PendingBillsAmount = 2890.5,
                InTransitBillsAmount = 1675.25,
                PaidBillsAmount = 15420.8,
                OverdueBillsAmount = 425,
                ApprovedBillsAmount = 3240.9,
                DisapprovedBillsAmount = 180,
                TotalBillsAmount = 25083.2,
            },
            PaypointLegalname = "Sunshine Services, LLC",
            PaypointDbaname = "Sunshine Gutters",
            PaypointEntryname = "d193cf9a46",
            ParentOrgName = "PropertyManager Pro",
            ParentOrgId = 1000,
            CreatedDate = DateTime.Parse(
                "2022-07-01T15:00:01.000Z",
                null,
                DateTimeStyles.AdjustToUniversal
            ),
            LastUpdated = DateTime.Parse(
                "2022-07-01T15:00:01.000Z",
                null,
                DateTimeStyles.AdjustToUniversal
            ),
            RemitAddress1 = "123 Walnut Street",
            RemitAddress2 = "Suite 900",
            RemitCity = "Miami",
            RemitState = "FL",
            RemitZip = "31113",
            RemitCountry = "US",
            PayeeName1 = "payeeName1",
            PayeeName2 = "payeeName2",
            CustomField1 = "",
            CustomField2 = "",
            CustomerVendorAccount = "123-456",
            InternalReferenceId = 1000000,
            AdditionalData = null,
            ExternalPaypointId = "Paypoint-100",
            StoredMethods = new List<VendorResponseStoredMethod>() { },
        };
        var actualElement = JsonUtils.SerializeToElement(actualObj);
        var expectedElement = JsonUtils.Deserialize<JsonElement>(expectedJson);
        Assert.That(actualElement, Is.EqualTo(expectedElement).UsingJsonElementComparer());
    }
}
